.ORIG x3000

;your program starts here
;R0 serves as a register for temporary data.
;R1 serves as a counter for how many numbers are in the stack
;R2 is the Sentinel,also as the final result
;R3 is used to get the ascii 0 and 9, ALSO STORE ENTER TO CHECK TEH INPUT IS OVER.
LD R6 STACK_START

AND R0,R0,#0
AND R1,R1,#0

READ 
LD R3 NEG_ENTER
LDI R0,KBSR
BRZP READ
LDI R0,KBDR 
ADD R3,R3,R0
BRz CHECK_FOR_VALIDITY

STORE_INTO_STACK
STR R0,R6,#0
ADD R6,R6,#-1
;R6 IS THE TOS ,POINTING TO THE NEXT AVAILABLE SLOT.

ECHO
LDI R0,DSR
BRzp ECHO
LDR R0,R6,#1
STI R0,DDR
BR READ



CHECK_FOR_VALIDITY
;POP A NUMBER
ADD R6,R6,#1
STR R0,R6,#0

;CHECK 0-9
LD R3, ASCII_ZERO
NOT R3,R3
ADD R3,R3,#1
ADD R3,R0,R3
BRn RESULT

LD R3, ASCII_NINE
NOT R3,R3
ADD R3,R3,#1
ADD R3,R0,R3
BRp RESULT

;CHECK FOR UNDERFLOW
LD R0 STACK_START
ADD R1,R1,#1
NOT R0,R0
ADD R0,R0,#1
ADD R0,R0,R6
BRz RESULT

RESULT
ADD R1,R1,#-10
BRz VALID
BR INVALID


VALID
LD R0,VAL_MSG
PUTS 
BR TERMINATE

INVALID
LD R0,INV_MSG
PUTS 
BR TERMINATE

TERMINATE
HALT

NEG_ENTER       .FILL XFFF6
ASCII_NINE  .FILL X0039
ASCII_ZERO  .FILL X0030
STACK_START .FILL X4000
KBSR    .FILL xFE00
KBDR    .FILL xFE02
DSR     .FILL xFE04
DDR     .FILL xFE06
INV_MSG .STRINGZ "\nInvalid Phone Number."
VAL_MSG .STRINGZ "\nValid Phone Number."

.END
